kind: Deployment
apiVersion: apps/v1
metadata:
  name: chis-mini-cms
  namespace: default
  labels:
    app: chis-mini-cms
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chis-mini-cms
  template:
    metadata:
      labels:
        app: chis-mini-cms
        role: rolling-update
        build_number: '<TAG>'
    spec:
      containers:
        - name: chis-mini-cms
          image: 'bakcovn/chis-mini-cms:latest'
      imagePullSecrets:
        - name: regcred
  strategy:
    type: RollingUpdate
